import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#0f0f11',
  },
  content: {
    padding: 20,
    paddingTop: 56,
    paddingBottom: 40,
  },
  centerScreen: {
    flex: 1,
    backgroundColor: '#0f0f11',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  muted: {
    color: '#aaa6a0',
  },
  managerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  managerToggleText: {
    color: '#b8a98a',
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
    marginBottom: 18,
  },
  title: {
    color: '#f6f2ec',
    fontSize: 34,
    fontWeight: '600',
    marginBottom: 4,
  },
  subtitle: {
    color: '#aaa6a0',
    fontSize: 14,
  },
  filterScroll: {
    marginBottom: 14,
  },
  filterRow: {
    gap: 8,
    paddingRight: 4,
  },
  foodCard: {
    backgroundColor: '#18181c',
    borderColor: 'rgba(255,255,255,0.09)',
    borderWidth: 1,
    borderRadius: 18,
    padding: 14,
    marginBottom: 16,
  },
  foodTitle: {
    color: '#f2cc8f',
    fontSize: 12,
    textTransform: 'uppercase',
    fontWeight: '700',
    letterSpacing: 0.8,
    marginBottom: 10,
  },
  foodSummary: {
    backgroundColor: 'rgba(242,204,143,0.06)',
    borderColor: 'rgba(242,204,143,0.14)',
    borderWidth: 1,
    borderRadius: 14,
    padding: 12,
    marginBottom: 10,
    gap: 4,
  },
  foodSummaryText: {
    color: '#aaa6a0',
    fontSize: 13,
  },
  foodGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 10,
  },
  settingsButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderColor: 'rgba(255,255,255,0.16)',
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#18181c',
  },
  settingsButtonIcon: {
    color: '#b8a98a',
    fontSize: 14,
    lineHeight: 16,
  },
  settingsButtonText: {
    color: '#aaa6a0',
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  settingsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
    marginBottom: 18,
  },
  settingsBackButton: {
    borderColor: 'rgba(255,255,255,0.16)',
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  settingsBackText: {
    color: '#aaa6a0',
    fontSize: 12,
  },
  settingsCard: {
    backgroundColor: '#18181c',
    borderColor: 'rgba(255,255,255,0.09)',
    borderWidth: 1,
    borderRadius: 18,
    padding: 14,
    marginBottom: 14,
  },
  settingsSectionTitle: {
    color: '#6d6963',
    fontSize: 12,
    textTransform: 'uppercase',
    fontWeight: '700',
    letterSpacing: 0.8,
    marginBottom: 10,
  },
  accountLabel: {
    color: '#6d6963',
    fontSize: 12,
    marginBottom: 5,
  },
  accountEmail: {
    color: '#f6f2ec',
    fontSize: 15,
  },
  themeRow: {
    flexDirection: 'row',
    gap: 8,
  },
  themeButton: {
    flex: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    borderWidth: 1,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.025)',
  },
  themeButtonActive: {
    backgroundColor: '#b8a98a',
    borderColor: '#b8a98a',
  },
  themeButtonText: {
    color: '#aaa6a0',
    fontSize: 13,
    fontWeight: '700',
  },
  themeButtonTextActive: {
    color: '#0f0f11',
  },
  settingsHint: {
    color: '#6d6963',
    fontSize: 12,
    lineHeight: 17,
    marginTop: 10,
  },
  signOutButton: {
    backgroundColor: '#3a3430',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 4,
  },
  signOutButtonText: {
    color: '#f6f2ec',
    fontSize: 15,
    fontWeight: '700',
  },
  foodInput: {
    width: '48%',
    backgroundColor: '#1f1f25',
    borderColor: 'rgba(255,255,255,0.09)',
    borderWidth: 1,
    borderRadius: 12,
    color: '#f6f2ec',
    paddingHorizontal: 12,
    paddingVertical: 11,
    fontSize: 14,
  },
  foodAddButton: {
    backgroundColor: '#f2cc8f',
    borderRadius: 12,
    paddingVertical: 13,
    alignItems: 'center',
    marginTop: 10,
  },
  foodAddButtonText: {
    color: '#0f0f11',
    fontSize: 15,
    fontWeight: '700',
  },
  filterChip: {
    borderColor: 'rgba(255,255,255,0.12)',
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 13,
    paddingVertical: 8,
    backgroundColor: 'rgba(255,255,255,0.025)',
  },
  filterChipActive: {
    backgroundColor: '#b8a98a',
    borderColor: '#b8a98a',
  },
  filterChipText: {
    color: '#aaa6a0',
    fontSize: 12,
    fontWeight: '600',
  },
  filterChipTextActive: {
    color: '#0f0f11',
  },
  emptyBox: {
    padding: 24,
    alignItems: 'center',
  },
  nutritionCard: {
    backgroundColor: '#18181c',
    borderColor: 'rgba(255,255,255,0.09)',
    borderWidth: 1,
    borderRadius: 18,
    padding: 14,
    marginBottom: 16,
  },
  nutritionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  nutritionTitle: {
    color: '#f2cc8f',
    fontSize: 12,
    textTransform: 'uppercase',
    fontWeight: '700',
    letterSpacing: 0.8,
    marginBottom: 4,
  },
  nutritionSubtitle: {
    color: '#aaa6a0',
    fontSize: 12,
    lineHeight: 17,
  },
  nutritionToggleText: {
    color: '#b8a98a',
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  nutritionBody: {
    marginTop: 12,
  },
  nutritionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  nutritionField: {
    width: '48%',
  },
  nutritionLabel: {
    color: '#6d6963',
    fontSize: 11,
    textTransform: 'uppercase',
    marginBottom: 5,
  },
  nutritionInput: {
    backgroundColor: '#1f1f25',
    borderColor: 'rgba(255,255,255,0.09)',
    borderWidth: 1,
    borderRadius: 12,
    color: '#f6f2ec',
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
  },
  nutritionHint: {
    color: '#6d6963',
    fontSize: 12,
    lineHeight: 17,
    marginTop: 10,
  },
  categoryManager: {
    backgroundColor: '#18181c',
    borderColor: 'rgba(255,255,255,0.09)',
    borderWidth: 1,
    borderRadius: 18,
    padding: 14,
    marginBottom: 16,
  },
  categorySelectRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    marginTop: 10,
  },
  globalTaskButton: {
    width: 44,
    height: 38,
    borderRadius: 12,
    borderColor: 'rgba(255,255,255,0.12)',
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.025)',
  },
  globalTaskButtonActive: {
    backgroundColor: '#b8a98a',
    borderColor: '#b8a98a',
  },
  globalTaskButtonText: {
    color: '#aaa6a0',
    fontSize: 18,
    fontWeight: '700',
  },
  globalTaskButtonTextActive: {
    color: '#0f0f11',
  },
  managerTitle: {
    color: '#6d6963',
    fontSize: 12,
    textTransform: 'uppercase',
    fontWeight: '700',
    letterSpacing: 0.8,
  },
  categoryAddRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 12,
    marginBottom: 10,
  },
  categoryInput: {
    flex: 1,
    backgroundColor: '#1f1f25',
    borderColor: 'rgba(255,255,255,0.09)',
    borderWidth: 1,
    borderRadius: 12,
    color: '#f6f2ec',
    paddingHorizontal: 12,
    paddingVertical: 11,
    fontSize: 14,
  },
  categoryAddButton: {
    width: 44,
    borderRadius: 12,
    backgroundColor: '#b8a98a',
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoryAddButtonText: {
    color: '#0f0f11',
    fontSize: 24,
    fontWeight: '700',
    lineHeight: 26,
  },
  managerCategoryList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  managerCategoryChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    borderColor: 'rgba(255,255,255,0.12)',
    borderWidth: 1,
    borderRadius: 999,
    paddingLeft: 10,
    paddingRight: 6,
    paddingVertical: 6,
    backgroundColor: 'rgba(255,255,255,0.025)',
  },
  managerCategoryDot: {
    width: 7,
    height: 7,
    borderRadius: 999,
  },
  managerCategoryText: {
    color: '#aaa6a0',
    fontSize: 12,
  },
  progressTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    marginBottom: 14,
  },
  progressMain: {
    flex: 1,
  },
  progressHint: {
    color: '#6d6963',
    fontSize: 12,
    textTransform: 'uppercase',
    marginTop: 2,
  },
  progressChartWrap: {
    width: 100,
    alignItems: 'center',
    justifyContent: 'center',
  },
  managerDeleteButton: {
    width: 20,
    height: 20,
    borderRadius: 999,
    backgroundColor: 'rgba(224,110,110,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  managerDeleteButtonText: {
    color: '#e06e6e',
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 17,
  },
  emptyText: {
    color: '#6d6963',
    fontSize: 13,
  },
  logoutButton: {
    borderColor: 'rgba(255,255,255,0.16)',
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  logoutText: {
    color: '#aaa6a0',
    fontSize: 12,
  },
  dateNav: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 16,
  },
  dateButton: {
    width: 44,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#18181c',
    borderColor: 'rgba(255,255,255,0.09)',
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dateButtonText: {
    color: '#f6f2ec',
    fontSize: 20,
    fontWeight: '600',
  },
  actualRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 8,
  },
  actualInput: {
    width: 72,
    backgroundColor: '#1f1f25',
    borderColor: 'rgba(255,255,255,0.09)',
    borderWidth: 1,
    borderRadius: 10,
    color: '#f6f2ec',
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 13,
  },
  groupList: {
    gap: 14,
  },
  groupBlock: {
    gap: 8,
  },
  groupHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 4,
  },
  groupDot: {
    width: 7,
    height: 7,
    borderRadius: 999,
  },
  groupTitle: {
    color: '#aaa6a0',
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  groupCount: {
    color: '#6d6963',
    fontSize: 12,
    marginLeft: 'auto',
  },
  todayButton: {
    flex: 1,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#18181c',
    borderColor: 'rgba(255,255,255,0.09)',
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  todayButtonActive: {
    backgroundColor: '#b8a98a',
    borderColor: '#b8a98a',
  },
  todayButtonText: {
    color: '#f6f2ec',
    fontSize: 13,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  progressCard: {
    backgroundColor: '#18181c',
    borderColor: 'rgba(255,255,255,0.09)',
    borderWidth: 1,
    borderRadius: 18,
    padding: 18,
    marginBottom: 16,
  },
  progressPercent: {
    color: '#6dbf8e',
    fontSize: 42,
    fontWeight: '700',
    marginBottom: 14,
  },
  progressStats: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  statValue: {
    color: '#f6f2ec',
    fontSize: 22,
    fontWeight: '600',
  },
  statLabel: {
    color: '#6d6963',
    fontSize: 11,
    textTransform: 'uppercase',
    marginTop: 3,
  },
  error: {
    color: '#e06e6e',
    fontSize: 13,
    marginBottom: 10,
  },
  sectionTitle: {
    color: '#6d6963',
    fontSize: 12,
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  addCard: {
    backgroundColor: '#18181c',
    borderColor: 'rgba(255,255,255,0.09)',
    borderWidth: 1,
    borderRadius: 18,
    padding: 14,
    marginBottom: 14,
  },
  addCardHandleWrap: {
    alignItems: 'center',
    paddingVertical: 3,
    marginBottom: 4,
  },
  addCardHandle: {
    width: 32,
    height: 4,
    borderRadius: 999,
    backgroundColor: '#b8a98a',
    opacity: 0.55,
  },
  addCardHandleActive: {
    backgroundColor: '#b8a98a',
    opacity: 1,
  },
  input: {
    backgroundColor: '#1f1f25',
    borderColor: 'rgba(255,255,255,0.09)',
    borderWidth: 1,
    borderRadius: 12,
    color: '#f6f2ec',
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 15,
  },
  categoryRow: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  categoryChip: {
    borderColor: 'rgba(255,255,255,0.12)',
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 11,
    paddingVertical: 7,
    backgroundColor: 'rgba(255,255,255,0.025)',
  },
  categoryChipActive: {
    backgroundColor: '#b8a98a',
    borderColor: '#b8a98a',
  },
  categoryChipText: {
    color: '#aaa6a0',
    fontSize: 12,
  },
  categoryChipTextActive: {
    color: '#0f0f11',
    fontWeight: '700',
  },
  addMetaRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 10,
  },
  metaInput: {
    flex: 1,
  },
  addButton: {
    width: 48,
    borderRadius: 12,
    backgroundColor: '#b8a98a',
    alignItems: 'center',
    justifyContent: 'center',
  },
  addButtonText: {
    color: '#0f0f11',
    fontSize: 26,
    fontWeight: '700',
    lineHeight: 28,
  },
  tasksCard: {
    backgroundColor: '#18181c',
    borderColor: 'rgba(255,255,255,0.09)',
    borderWidth: 1,
    borderRadius: 18,
    overflow: 'hidden',
  },
  taskItem: {
    flexDirection: 'row',
    alignItems: 'stretch',
    borderBottomColor: 'rgba(255,255,255,0.09)',
    borderBottomWidth: 1,
  },
  taskItemDone: {
    opacity: 0.68,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 7,
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.25)',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 1,
  },
  checkboxDone: {
    backgroundColor: '#6dbf8e',
    borderColor: '#6dbf8e',
  },
  checkboxText: {
    color: '#0f0f11',
    fontWeight: '700',
  },
  taskBody: {
    flex: 1,
  },
  taskTitle: {
    color: '#f6f2ec',
    fontSize: 15,
    marginBottom: 4,
  },
  taskTitleDone: {
    textDecorationLine: 'line-through',
    color: '#6d6963',
  },
  taskMeta: {
    color: '#aaa6a0',
    fontSize: 12,
    marginBottom: 3,
  },
  taskSub: {
    color: '#6d6963',
    fontSize: 12,
  },
  taskMain: {
    flex: 1,
    flexDirection: 'row',
    gap: 12,
    padding: 14,
  },
  deleteButton: {
    width: 46,
    alignItems: 'center',
    justifyContent: 'center',
    borderLeftColor: 'rgba(255,255,255,0.09)',
    borderLeftWidth: 1,
  },
  deleteButtonText: {
    color: '#e06e6e',
    fontSize: 24,
    lineHeight: 26,
    fontWeight: '600',
  },
  taskActions: {
    width: 46,
    borderLeftColor: 'rgba(255,255,255,0.09)',
    borderLeftWidth: 1,
  },
  taskActionButton: {
    flex: 1,
    minHeight: 42,
    alignItems: 'center',
    justifyContent: 'center',
  },
  globalTaskActiveIcon: {
    color: '#b8a98a',
    fontSize: 17,
    fontWeight: '700',
  },
});